name = "CompPolyEval"
version = "0.1.0"
defaultTargets = ["comppolyeval"]

[[lean_lib]]
name = "CompPolyEval"

[[lean_lib]]
name = "Hax"
srcDir = "HaxLib"

[[lean_exe]]
name = "comppolyeval"
root = "Main"

[[require]]
name = "CompPoly"
git = "https://github.com/Verified-zkEVM/CompPoly"